# Generated by Django 4.2.11 on 2026-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(upload_to='inputs/')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('rows_input', models.IntegerField(default=0)),
                ('rows_output', models.IntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
